### PR TITLE
First Commit

### PR DESCRIPTION
**Pull request by KaitouKid1412**
This code needs working on.
Pulled request anyway.

### CODE REVIEW

**Comment by Nischay-Pro** [comment]
Please make a directory called chat and push all your code into chat

Make a directory called schema and write the sql files for your database and table.

**Comment by aero31aero** [comment]
Some minor suggestions. Please try to not write vanilla PHP and consider using a basic template engine for your views(html pages). That would result in some clean code.

**Comment by Nischay-Pro** [comment]
Make them target lavarel?

**Comment by Nischay-Pro** [comment]
Please put your code into a directory.

**Pull request closed without merging**
