### PR TITLE
Gravator and CKEditor

### PR DESCRIPTION
**Pull request by tusharaherkar**

### CODE REVIEW

**Comment by Nischay-Pro** [comment]
Are you using the same database.php file? Please try ensuring uniformity in the code.

**Review by aero31aero — CHANGES_REQUESTED** [review]
ckeditor seems to be something that already has its own repo somewhere. We shouldn't pull this into our codebase but instead use a simple way to manage dependencies instead. This isn't a small project so we shouldn't polute our repository with it.

**Comment by Nischay-Pro** [comment]
I think he customized the ckeditor. ckeditor allows you to build your own flavors of it.

**Comment by tusharaherkar** [comment]
@Nischay-Pro hey i am using the sql file which is there in the schema folder which has database name as "crux" and for database accessibility inside webapp ( database.php ) database name was different that is "test" so i changed that name to "crux"

**Comment by Nischay-Pro** [comment]
I recommend instead of using the entire ckeditor folder and dumping the source code onto the project, use a CDN

https://cdn.ckeditor.com/

Have a look at this @tusharaherkar

**Comment by tusharaherkar** [comment]
hey @Nischay-Pro i have used the same bro in actual code. I have told this before also. see my code
https://github.com/crux-bphc/chat-forum/pull/4/commits/4b45407552a6acafaec253727bafb67e0f2697a1

**Comment by aero31aero** [comment]
But the fact remains that this PR adds the whole of ckeditor into our repository. Please remove that commit from this PR, preferably using interactive rebase.

**Comment by Nischay-Pro** [comment]
Why does your code have translation files?

**Comment by aero31aero** [comment]
Closing this as inactive. @ayushiaks can you take this one over if the changes are still necessary?

**Pull request closed without merging**
